nodeLinker: node-modules
enableGlobalCache: true
npmRegistryServer: "https://registry.npmjs.org"
supportedArchitectures:
  os: ["darwin", "linux"]
  cpu: ["x64", "arm64"]

yarnPath: .yarn/releases/yarn-3.1.0.cjs